### ISSUE TITLE
Duplicate Table

### ISSUE THREAD

**Issue by LawrenceUWD** [JohnTendik/jtrt-tables#11]
Hi

I am trying to duplicate a table. I have tried the Wordpress Duplicate This plugin, as well as duplicating the post in the database with PHP MyAdmin.

It duplicates the table, but it does not pull my table entries into the duplicated post. How can I fully duplicate a table?

It's a table with lots of entries and the first column contains hyperlinks. I do not look forward to creating a new table and entering over 100 hyperlinks again :(

If you can assist I would be really thankful.

Kind Regards,
L

**Comment by LawrenceUWD** [comment]
Update:

I figured out how to duplicate a table within the database.

In the Wordpress backend, create a new table in JTRT Tables and save it. Once saved, in the database root navigate to jtrt_tables and find the table you want to make a copy of and copy it. Then change the jttable_IDD to the table ID generated by the JTRT table creator. Also change the ID generated in the object_type to the new ID and save the edits.

In the Wordpress backend, refresh and the table will be there under your JTRT tables.

JohnTendik, perhaps implementing a table duplication option in future would be a good idea? :)

**Comment by JohnTendik** [comment]
Hey Lawrence, 

The plugin table uses its own custom db table so I don't think a duplicator plugin will work 100% :P I'm really glad however you were able to find a quick and dirty solution to your issue :P I really like that suggestion of duplicating tables, I'm sure it will come in handy for many users. I will definitely look into making that a possibility :P 

I'm going to mark this as solved for now, If you have any more issues or suggestion/feedback please feel free to contact me.

Thanks for using my plugin and the suggestion! 
John
