### ISSUE TITLE
Problem with hiding columns

### ISSUE THREAD

**Issue by fzdaflaki** [JohnTendik/jtrt-tables#12]
I have installed your excellent plugin on our website, but hiding columns not working at all, I tried different breaking point but all columns are visible ! can you help me? 
i suddenly discovered when Show Title is disabled, hiding columns not working but after enable table title
columns hide correctly!!

**Comment by JohnTendik** [comment]
Woah, that's an interesting problem.

So you're saying when you have Show Title option enabled the breakpoints work? That's super weird and this is the first time I've heard this come up. 

Are you using v3+? 
What version of Wordpress are you running?
Do you know what version of PHP is running on your server?

Also is there a website link I can visit to check out the issue? If you can put up a table on a test page with the issue present, I can take a look at it through the console tools to see if I can find an issue that way.

Thanks for using my plugin and providing feedback! 
John

**Comment by fernandocoello** [comment]
In my opinion the problem appears when you select "Small". If Small is active never hides any column.

**Comment by JohnTendik** [comment]
Hey fernandocoello ,

That may be due to the size of the available width. Did you set custom breakpoints(sizes) above in the table options section? 

Thanks
John

**Comment by JohnTendik** [comment]
Hey guys, 

I'm closing this issue, I'm hoping this issue is solved in the new update. If there are any issues you come across please do create a new ticket and I will do my best to help out. 

Thanks 
John
