### ISSUE TITLE
Nivo Slider

### ISSUE THREAD

**Issue by greenpeteuk** [JohnTendik/jtrt-tables#14]
It seems this plugin may have issues with one of the Nivo sliders, It certainly did on a site I administer.
Unfortunately I cannot tell you the exact plugin as after uninstalling the slider, I couldn't find it again to re-install and I didn't keep a note of the name :-\

I have installed a new slider and all is good! :-) 

Also, It would be great to be able to nest cells so it's possible to have a different number of columns on each row as you can using tables.

**Comment by JohnTendik** [comment]
Hey greenpeteuk,

Thank you for bringing this to my attention, I will try to dig around in my free time to see if I can pin point the issue. 

As for the nesting cell suggestion I think that's a great idea. I will look into this and see if I can make it happen. My immediate guess is that it may have some issues with the responsive parts (not knowing how many columns to hide) but if its possible I will try to make this happen :P 

Thanks for using my plugin and providing feedback/suggestions, if you run into any issues or have questions please let me know i'd be glad to help. 

John

P.S. I'm closing this for now, if you run into the same issue again feel free to reopen it.
