### ISSUE TITLE
Copy or export Table

### ISSUE THREAD

**Issue by fernandocoello** [JohnTendik/jtrt-tables#17]
Hi! Really great plugin, thanks for it.

Well, i'm not sure if this can be considered an issue, but for me is a problem the lack of an option to copy tables. I need to create about 30 tables with the same style and layout, but I have not CSV, then an option for copy tables may be great.

What the people think about it?

Thanks in advance

**Comment by JohnTendik** [comment]
Hey, 

That's a great idea that has been mentioned once before :P I'm totally going to work on making this a feature since lots of people think its a good idea. 

I'll post here to notify you when that feature is ready.

Thanks for the suggestion! 
John

**Comment by fernandocoello** [comment]
Oh! Sorry... I viewed it latter :)

**Comment by JohnTendik** [comment]
Hey,

The new update includes a very very advanced editor. You can simply copy paste your entire table for easy duplication however this wont copy over the styles so I will make a duplicate option for the new update. For now however I'm closing this topic, if you have any more suggestion please let me know and I will try to include them in the plugin. 

Thanks
John

**Comment by JohnTendik** [comment]
Duplicate is now possible. Export to CSV is also possible. 

Thanks for the suggestion! 
John

**Comment by fernandocoello** [comment]
You are great man!!!
