### ISSUE TITLE
Insert graphics or hyperlinks?

### ISSUE THREAD

**Issue by avwebmaster** [JohnTendik/jtrt-tables#21]
You can see what I'm looking for by scrolling to the bottom on this page:

http://jam.avwebmaster.com/products/minutes/

To the right of Pricing.  Conceptually it's clear, but I don't think you can handle the back end to this.  I think you just handle text, right?

**Comment by JohnTendik** [comment]
Hello avwebmaster,

HTML is supported, so yes images and links are possible. You can easily insert links or images using the backend editor. For links there are two ways to do it, one would be to use the editor tool bar, there is a paperclip icon, or you can use the menu bar Insert -> insert Link or insert image

![](https://ps.w.org/jtrt-responsive-tables/assets/screenshot-2.jpg?rev=1541631)

As you can see from the image above, there is a menu bar with the titles File Edit Insert Format etc etc

Under the Insert menu bar, you can insert images that way.

Hope this answers your question, if you have any more questions or comments please reopen the ticket and I will do my best to help out

Thanks
John

**Comment by avwebmaster** [comment]
Don't know if you got the recent one (#23?) but can I put text above the graphic link?

**Comment by JohnTendik** [comment]
Hey, 

Yeah you should be able to but as you said <br> isn't working. I will fix this up for you so look out for an update today.

Thanks
John
