### ISSUE TITLE
Thanks.  How do I add text above the graphic link? <br. doesn't seem to work

### ISSUE THREAD

**Issue by avwebmaster** [JohnTendik/jtrt-tables#23]

**Comment by JohnTendik** [comment]
Hey, 

You're right, <br> doesn't seem to work for some reason. I'm working on an update right now, I will include this as a fix. 

Thank you for bringing this up, if you have any further issues or questions please feel free to contact me
John

**Comment by JohnTendik** [comment]
Hey, I fixed this up for you so now <br> tag should work giving you the ability to add text above the image. While at it I also implemented support for the following tags as well. 

<em><b><strong><a><u><big><img><i><br><caption><figure><span><hr><ul><li><dl><dd><dt><form><input><div><select><option>

Hope this helps, thanks again for bringing this to my attention so I could fix it. If you run across any more issues please let me know.

Thanks
John
