### ISSUE TITLE
Ctrl+ click doesnt work to select mulitpe columns

### ISSUE THREAD

**Issue by Lbischoff** [JohnTendik/jtrt-tables#30]
You cant ctrl+ click to select mulitple columns if you want to set different columns with different attributes in table editor.  Shift+click does but of course it does point to point selection.  If it's not clear, I want to select every other column, Ctrl+Click should do i.e. column 1 and 3 selected, shift+click selects columns 1 through 3.

**Comment by JohnTendik** [comment]
Hello Lbischoff, 

Ctrl + click is not a feature unfortunately :( I will look into ways for making this a possibility but for the time being this is not possible. Only shift + click is supported. 

Thanks
John
