### ISSUE TITLE
Shortcode question

### ISSUE THREAD

**Issue by visualpoetics** [JohnTendik/jtrt-tables#31]
Is it possible to embed something inside a cell using a shortcode (i.e. embedding an audio player)

Thanks

**Comment by JohnTendik** [comment]
hello @visualpoetics 

Yes, it _should_ work but as I look at the code now, I don't think it will. A quick fix would be to update this file: 

jtrt-tables/admin/partials/jtrt-adminClass-shortcode.php

line: 107

` $html .= "<td>" .preg_replace("/[\n\r]/","<br>",$cell). `"</td>";`

change it to this:

` $html .= "<td>" .do_shortcode(preg_replace("/[\n\r]/","<br>",$cell)). `"</td>";`

**Comment by condog72** [comment]
Hi love the plugin, but cant get it to work with short code using the above
any change along this line cause an error

**Comment by JohnTendik** [comment]
hey @condog72 

Try replace the jtrt-adminClass-shortcode.php file with this 
https://gist.github.com/JohnTendik/9ff16c922075e7283ce4ef96c7424af6

**Comment by jodylecompte** [comment]
@condog72 , @visualpoetics I have created a pull request for this issue and @JohnTendik will get it merged in hopefully tomorrow.
