### ISSUE TITLE
html allowable

### ISSUE THREAD

**Issue by avwebmaster** [JohnTendik/jtrt-tables#33]
first John, Thank you thank you for the example you created for me in jam.avwebmaster.com

Where do I give you kudos.

Second, how do I add a break into the row to house my 2 entries

<a href="https://jamllc.infusionsoft.com/saleform/nathniet">$997 Yearly</a><p><a href="https://jamllc.infusionsoft.com/saleform/nathnirt">Pay Monthly - $97 a month (12 month contract)</a></b>

I tried <b> <p> even the Alt-enter as I would in Excel.

Paul

**Comment by JohnTendik** [comment]
Hi Paul, 

I totally forgot I was working on your table, I've been sidetracked with work and school. 

The two pages you linked, I couldn't find JTRT table present, are you sure those are the right pages? As for adding a break into the row, ALT+enter should work, if it does not you can try the html tag <br> which does the same thing. An example usage of this tag would be like this:

`This is my cell value on the top row<br>This is my cell value below that`

This will be printed out like this:

`This is my cell value on the top row
This is my cell value below that`

**Comment by avwebmaster** [comment]
_Your_ table is test 2.  Nope, Alt Enter does NOT work.

**Comment by avwebmaster** [comment]
What I want is in 2 boxes up, but with just a break.

$997 Yearly (Pay annually)

Pay Monthly - $97 a month (12 month contract) contract)

**Comment by avwebmaster** [comment]
Let me know if Alt Enter DOES work as I have cache issues on my machine.

Thank you, love your work

**Comment by jodylecompte** [comment]
@avwebmaster The keyboard shortcut is CTRL + Enter on Windows and Linux; I don't have a mac machine to test on but I suspect it would be Command + Enter on mac.

@JohnTendik This can likely be closed, unless you want README updated to contain this information somewhere.
