### ISSUE TITLE
Unable to sort table: e.push is not a function

### ISSUE THREAD

**Issue by ottosson** [JohnTendik/jtrt-tables#34]
I'm having trouble with sorting table columns. Nothing happens when I push the sort buttons and I get a console error: `Uncaught TypeError: e.push is not a function`

I'm using WordPress 4.7.3 and JTRT 4.1

**Comment by JohnTendik** [comment]
Hey thanks for letting me know, is this happening for "column hiding" responsive option or the regular scroll/stack? I'll do some testing and get back to you asap.

**Comment by JohnTendik** [comment]
Hey ottosson, 

I found out the problem, I will include this fix in the future update but for now you can fix this by adding an order option to the DataTable options located in jtrt-responsive-tables-public.js file

`var jtrtDTcopy = mytablr.DataTable({
					"paging":isPaged,
					"searching":isSorted,
					"ordering":true,
					**"order": [],**
					"info":false,
					"language": {
						"emptyTable":     translation_for_frontend.emptyTable,
						"info":           translation_for_frontend.info,
						"infoEmpty":      translation_for_frontend.infoEmpty,
						"infoFiltered":   translation_for_frontend.infoFiltered,
						"lengthMenu":     translation_for_frontend.lengthMenu,
						"search":         translation_for_frontend.search_string,
						"zeroRecords":    translation_for_frontend.zeroRecords,
						"paginate": {
							"first":      translation_for_frontend.first,
							"last":       translation_for_frontend.last,
							"next":       translation_for_frontend.next_string,
							"previous":   translation_for_frontend.prev_string
						},
					}
				});`

simply add the option "order" which will hopefully solve your issue.

Let me know if this helps,

thanks again for bringing this to my attention!
John

**Comment by ottosson** [comment]
Awesome! Thanks for the fast reply. Works like a charm!

**Comment by sonianand11** [comment]
Works for me. Thank you @JohnTendik
