### ISSUE TITLE
Won't let me insert an image.

### ISSUE THREAD

**Issue by markround2** [JohnTendik/jtrt-tables#37]
When I try to insert an image into the table, it displays "Making Calculations - Please Wait" and then never returns.

**Comment by JohnTendik** [comment]
Hey,

I have a few questions, if you can answer them it would definitely help me out in narrowing down the issue. 

1) WordPress version
2) Plugin Version
3) Have you cleared your cache? Do you have caching enabled / have plugins?
4) PHP Version for your server if you can get that info

Also, when the plugin hangs at the making calculations loading screen, can you right click on the page > select _Inspect_ element -> console tab 

You should probably see an error message in the console tab, can you copy paste the error code here if there is any (most likely there is) 

Thank you! 

John

**Comment by markround2** [comment]
Wordpress 4.7.3
Plugin Version 4.1
Php Version 5.5

Mark Round
805-210-0749
mark.c.round@gmail.com

**Comment by JohnTendik** [comment]
Hey Mark, 

Thanks for the update, unfortunately this doesn't help me much, I have the exact same environment setup on one of my local copies and I could not reproduce the error. 

Did you try clearing the cache? Also can you check to see if you get any errors in the console? ( right click click on the page > select Inspect element -> console tab )

I'll keep trying to reproduce the issue, but I have a feeling it may be because of caching issue. 

Also, you can always insert images directly into the cell by typing out the img tag inside the cell like so:
`<img src="linktoimage.png" alt="describe image">` 

Thanks
John

**Comment by ckFMB** [comment]
Thanks for the great plugin, but I'm having the same issue.  Here's what the console tells me in Firefox:

TypeError: "\n\t\t<div class=\"media-modal wp-core-ui\">\n\t\t\t<button type=\"button\" class=\"button-link media-modal-close\"><span class=\"media-modal-icon\"><span class=\"screen-reader-text\">Close media panel</span></span></button>\n\t\t\t<div class=\"media-modal-content\"></div>\n\t\t</div>\n\t\t<div class=\"media-modal-backdrop\"></div>\n\t" is not a function

wp.template</< ***/wp-admin/load-scripts.php:70:283
wp.Backbone.View<.render ***/wp-admin/load-scripts.php:71:2906
[53]</d<.attach ***/wp-admin/load-scripts.php:134:19754
[53]</d<.open ***/wp-admin/load-scripts.php:134:20152
[50]</</d.prototype[a] ***/wp-admin/load-scripts.php:134:17630
JTrtEditor.prototype.renderMediaUploader/< ***/wp-content/plugins/jtrt-responsive-tables/admin/js/vendor/jtrt-responsive-tables-class.js:836:13

(I removed the address of the intranet site where I'm running Wordpress and replaced it with *** in the snippet above.)

I'm using Wordpress 4.7.3 and version 4.1 of your plugin.
Hopefully that is helpful.

**Comment by JohnTendik** [comment]
Hey ckFMB 

I'm sorry you're running into this issue. As a temporary fix, you could always try inserting plain html into the cell to get your image. 

`<img src="linktoimage.png" alt="describe image">` 

I know this isn't pretty but until I can reproduce this and find a fix for it, its the only way to insert images it seems. The error message you've given me tells me the wp-media file_frame.open() function is failing. I'll try to take a look at whats going wrong and hopefully get back to you guys with a fix asap. 

Thanks
John

**Comment by markround2** [comment]
No problem.  Worked around it with no images for now.  Take your time.  Appreciate it.

Mark Round
805-210-0749
mark.c.round@gmail.com

**Comment by satun14** [comment]
Ahaha, really?!
Enable JetPaсk - connect to Wordpress.com and get http://clip2net.com/s/3KH2wv1
Turn offJetPaсk  and everything works ...
Please fix it!

**Comment by JohnTendik** [comment]
Guys sorry for getting to this so late, it was a weird one that I kept running away from but I believe I have solved the issue! :P Please update to the latest version and let me know if this issue still persists. 

Thanks for all your patience.
JT
