### ISSUE TITLE
JTRT tables v4.1 for Wordpress, menu does not work?

### ISSUE THREAD

**Issue by myonkyo** [JohnTendik/jtrt-tables#38]
WP 4.7.3 installed, download and active the plugin seem no problem, also, I could add a new table, modify the values. 
But every function in menu does not work, I can unfold the menu and click, but nothing has happened. 

I like your work very much, could you please help me?

**Comment by JohnTendik** [comment]
Hey,

Can you elaborate more on which items don't work? Some of the buttons require that you have a cell selected, if you don't have a cell selected your changes work work. 

If the table editor ever hangs at "making calculations" screen, then please right click on the page > select _inspect_ element > console tab

Whatever is inside the console tab, there should be some sort of error message, copy paste what you see into here and I'll take a look at the problem.

Thank you

John

**Comment by myonkyo** [comment]
Hey, John

Thanks for your fast response. in my case, every button does not work, include import and export menu. Can you please tell me how to get in to the console tab?

Best, Monkyo

**Comment by JohnTendik** [comment]
Hey,

If you can get me errors from the console tab it would definitely help me out. Also can you can provide your plugin version, WP version and PHP version.

To get to the console tab, just follow these steps (on the table editor page where the issue happens)

right click on the page > select inspect element > console tab
(in chrome f12 also brings up the dev tools)

Thanks
John
