### ISSUE TITLE
Not saving rows

### ISSUE THREAD

**Issue by luisolis1** [JohnTendik/jtrt-tables#39]
Hello John
Thank you for your table plugin. I'm trying to build a new table and everything looks fine , the problem comes when I try to insert a new row and update it; is not saving and then show a "Page not found" error.

I'm working on Chrome and made taste of this problem in Firefox, and runs in the same way.
I'm using plugin Version 4.1 and WordPress 4.7.3

I appreciate your time.

**Comment by JohnTendik** [comment]
Hey,

Are you by any chance trying to view the table by clicking the preview button? Unfortunately that's not working :/ you have to add the shortcode in a page, widget, or post for the table to show up.

Is the page not found error happening directly after saving? If so, then you may have an issue with your server. 

Also, can you try and see if there is anything in the console? Sometimes if there are issues an error message will be displayed in the console, this would help me narrow the issue down. 

Thanks
John.

**Comment by JohnTendik** [comment]
may be related:

https://github.com/JohnTendik/jtrt-tables/issues/40#issuecomment-290880510
