### ISSUE TITLE
How do you merge table cells?

### ISSUE THREAD

**Issue by digitalflash** [JohnTendik/jtrt-tables#51]

**Comment by JohnTendik** [comment]
Unfortunately this feature is not available. I tried it a lot, however with merged cells, it makes responsive part of the tables act really weird. I decided to hold off on this but I will do more testing on this when I get back from my vacation but I cannot promise anything. The point of the plugin is to be able to create responsive tables, so I cannot mess that up. 

Sorry for the inconvenience, if you have any other questions or concerns please let me know I will do my best to help out. 

Thanks
John
