### ISSUE TITLE
Insert button in table

### ISSUE THREAD

**Issue by draxx318** [JohnTendik/jtrt-tables#55]
So i'm trying to insert a custom button created with Buttons X plugin inside a table but after linking the shortcode it just wont show up (shortcode is displayed as text). Is there any way to fix this?

**Comment by JtLively** [comment]
Have you tried using any of this as a workaround?
http://diythemes.com/thesis/wordpress-shortcodes/

**Comment by JohnTendik** [comment]
I'm going to be releasing an update sometime this week with a few simple fixes. The shortcode issue is part of the fix. I apologize for such a long delay.

**Comment by jodylecompte** [comment]
@draxx318 I have created a pull request for this issue and @JohnTendik will get it merged in hopefully tomorrow.
