### ISSUE TITLE
Wrapping text around images

### ISSUE THREAD

**Issue by mclift7425** [JohnTendik/jtrt-tables#56]
Fairly new to JTRT Tables - works great on the other tables I've created. Just having this issue with one table:

I am inserting an image into a cell. I need to include attribution info for the pic so I used "align='middle'" but the text gets cropped off on the right side. I tried CTRL-Enter to force-wrap the text to the next line, but that causes the cropped text to appear below the pic instead of under the text (i.e. "wrap").

![jtrttablewraptext](https://user-images.githubusercontent.com/31021201/29296665-91ed1686-8110-11e7-85ce-126c0b5e4329.jpg)

I also looked for a way to set the width of the column smaller to force text to wrap, but as the table is only one column width, I could not find an option to do that.

Thanks again for your excellent plug-in. I appreciate your help finding a solution.

Rick

**Comment by JtLively** [comment]
Did you try a `<BK />` or wrapping the text in a div?

**Comment by JohnTendik** [comment]
Hey,

Cant tell if this is the issue but maybe the line-height may be pushing the text below the image. Do you have a link where I can go in and see the problem? It can probably be solved with some simple css but I cant tell what would be required just from a picture. 

As for your other question, setting the column width is currently not a feature but it has been mentioned before and is on the to do list.

**Comment by JohnTendik** [comment]
Closing due to no response. Cleaning up issues. Feel free to open again if this is still an issue for you.
