### ISSUE TITLE
hiding columns 

### ISSUE THREAD

**Issue by binarylab1** [JohnTendik/jtrt-tables#58]
HI,
in the details, it says you can hide columns by just selecting which ones to hide, but I just cannot find this option on mine. I am using version 4 on WP.
kind regards
Jon

**Comment by JtLively** [comment]
Have you checked out Footables ?
https://github.com/fooplugins/FooTable
https://github.com/fooplugins/FooTable/blob/V2/README.md

**Comment by JohnTendik** [comment]
@binarylab1 In the table options you can select "column hiding" and then use the button that looks like two columns on the table editor to select which columns to hide. I'm hoping to create a video tutorial soonish so its more clear. 

Thanks
JT
