### ISSUE TITLE
Can't Export Table

### ISSUE THREAD

**Issue by JtLively** [JohnTendik/jtrt-tables#60]
Are there specific requirements before being able to export the table ?

**Comment by jodylecompte** [comment]
@JtLively You should be able to click export and immediately have the file download in .csv once you do so. If you are still having this issue, please let us know.

**Comment by JtLively** [comment]
@jodylecompte I'm unable to do so. Next time I see an update I'll try again.

**Comment by mikeyea22** [comment]
I have the same problem here, the menu option "export table" simply does nothing, even after upgrading to the latest version 4.1.2. What I find interesting and is maybe related: there is a cursor blinking right in the menu option!

**Comment by jodylecompte** [comment]
@mikeyea22 Thanks for letting us know. What version of WordPress are you using and which browser / browser version?

**Comment by JohnTendik** [comment]
@mikeyea22 @JtLively can you guys check your console to see if there are any errors being shown? 

Thanks
JT

**Comment by mikeyea22** [comment]
Thank you for trying to dive into the problem. I have two websites, one with WP4.6.1, the other with 4.9.3. The behaviour is the same in both versions.
For standard use I have firefox 56.0.1 64bit in which exporting doesn't work (as described). Same with Microsoft Edge 41.16299.15.0. 
The browser which behaves correctly, though, is Google Chrome 64.0.3282.140!
There is no entry in the firefox console. But, when I try to close the window of the Edge browser after trying to CSV download, I get a warning "hello, your data are still being downloaded...". I have attached the box here:
![2018-02-12](https://user-images.githubusercontent.com/36201227/36094550-ffc3d182-0fee-11e8-858d-ddcd89dfe34d.png)

**Comment by JohnTendik** [comment]
@mikeyea22 Thanks for bringing this to my attention. This has now been fixed. It will be released with a future update. :)

**Comment by mikeyea22** [comment]
Thank you for caring The fix doesn't seem to have made it into 4.1.3, so I will sit and wait ;-)

**Comment by JohnTendik** [comment]
@mikeyea22 I have released an update, please let me know if it has fixed your issue :) If you run into any more issues or have questions feel free to open up another ticket. 

Thanks
JT

**Comment by mikeyea22** [comment]
Hallo John,
I have just updated to 4.1.5, but still there is no change in behavior :-(

**Comment by mikeyea22** [comment]
John, please don't bother! Everything is working correctly, I am really sorry! As I said before, I have two sites with almost identical content, and I mixed up the site in which I updated the plugin with the site without update  :-((
Sorry again
Mike
