### ISSUE TITLE
+ in front of my text

### ISSUE THREAD

**Issue by FireDept** [JohnTendik/jtrt-tables#64]
Hey,

You've got me stumped. How I get the + in front of my text to display additional texts?

The picture with the + : https://ps.w.org/jtrt-responsive-tables/assets/screenshot-4.jpg?rev=1448376

**Comment by JohnTendik** [comment]
You would have to setup responsive options in the table settings area =) 

I apologize for the late response, unfortunately I do not have time anymore to take care of this project so support is basically non existent at this point.

**Comment by jodylecompte** [comment]
@FireDept Did enabling responsive options address your issue?

**Comment by FireDept** [comment]
Hey,
yeah of curse. But now I don't see anything of my table. It's not loading.
![table](https://user-images.githubusercontent.com/35640904/35876408-798b8c5c-0b72-11e8-9e72-68d4a3677d22.png)

Is it possible to use the expand also in the desktop view and list certain content there?
