### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by aschobey** [JohnTendik/jtrt-tables#8]
I'm getting the following in the Table Column editor. What am I doing wrong? CVS file is attached.

error on line 2: Item count (2) does not match header count (7) error on line 3: Item count (2) does not match header count (7) error on line 4: Item count (2) does not match header count (7) error on line 6: Item count (6) does not match header count (7) error on line 7: Item count (2) does not match header count (7) error on line 8: Item count (3) does not match header count (7) error on line 9: Item count (2) does not match header count (7) error on line 11: Item count (6) does not match header count (7) and so on...

[18-Packaging Solutions-2016-02-18.zip](https://github.com/mythirdeye/jtrt-tables/files/137114/18-Packaging.Solutions-2016-02-18.zip)

**Comment by JohnTendik** [comment]
Hey I'm closing this issue due to the new update. Most of the CSV related issues should be solved as I started using a more enhanced converter. If you have any issues regarding the newer version of the plugin please let me know. 

John
