### ISSUE TITLE
How to assign row filter to 25 or 50 or 100?

### ISSUE THREAD

**Issue by baripov** [JohnTendik/jtrt-tables#85]
Hi! Very good plugin to use and simply to understand! I need to assign different number for show another quantity of rows. For example, by default is showing 10 rows per page. How to assign 50 or 100 by default? Thank you!

**Comment by JohnTendik** [comment]
Hey,

I replied to your email and how you can update the default. I may do an update to possibly include this as an option, currently its not possible.
