### ISSUE TITLE
No Columns Supplied?

### ISSUE THREAD

**Issue by JohnPaulWalsh** [JohnTendik/jtrt-tables#9]
I just get 'No Columns Supplied' as a console error no matter which breakpoint I'm viewing it at or what columns were selected

The table appears fine on the dashboard section after generating?

[parkrun-13-3-16.zip](https://github.com/JohnTendik/jtrt-tables/files/171275/parkrun-13-3-16.zip)

**Comment by JohnTendik** [comment]
Hey I'm closing this issue due to the new update. Most of the CSV related issues should be solved as I started using a more enhanced converter. If you have any issues regarding the newer version of the plugin please let me know. 

John
