### ISSUE TITLE
help

### ISSUE THREAD

**Issue by muhacolee4** [JohnTendik/jtrt-tables#91]
please how do i display the table using php instead of  short because i want display table based on condition , help need asap

**Comment by JohnTendik** [comment]
Hey,

You can do 

```
<?php

// your conditional code
if (whatever) {
  do_shortcode('[jtrt_tables id="something"]');
}

?>
```

**Comment by muhacolee4** [comment]
Let try this again because I tried pay a variable to the ID before and was
having issue

Something

$value=4;
And then passing value into the php eg  Id="$value" sorry for the way I
type, I am on phone now

**Comment by JohnTendik** [comment]
then you have to do 

`do_shortcode("[jtrt_tables id='$value']");`

the double quote need to be on the outside and single quotes in the inside. PHP variables are only parsed inside double quotes but if you start off as single quotes its not going to work (at least thats my guess, I havent tried it) 

or 

`do_shortcode('[jtrt_tables id=" ' . $value . ' "]');`

**Comment by muhacolee4** [comment]
It work thanks alot bro,I would like to be your friend on Whatsapp if you
don't because I hope to be u or better than I someday

On Aug 10, 2019 5:59 PM, "John Tendik" <notifications@github.com> wrote:

then you have to do

do_shortcode("[jtrt_tables id='$value']");

the double quote need to be on the outside and single quotes in the inside.
PHP variables are only parsed inside double quotes but if you start off as
single quotes its not going to work (at least thats my guess, I havent
tried it)

or

do_shortcode('[jtrt_tables id=" ' . $value . ' "]');

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JohnTendik/jtrt-tables/issues/91?email_source=notifications&email_token=AG7XFNBDZZETBBIETDNTBG3QD3XYDA5CNFSM4IKZORXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4ARJFI#issuecomment-520164501>,
or mute the thread

**Comment by muhacolee4** [comment]
Bro, I need another urgent help, I am really sorry for disturbing you,
please I need to all rows with a field e.g absent and also filter the field
present and then display using the shortcode, from your table, I could only
filter column by number , is it possible to filter by content like I said
filter the rows that are absent and display it

**Comment by JohnTendik** [comment]
No, filter by content is not a feature at this.

You could however use javascript after page load to filter the table..

**Comment by muhacolee4** [comment]
Ok thanks bro
