### ISSUE TITLE
Image Alignment

### ISSUE THREAD

**Issue by Rashuz** [JohnTendik/jtrt-tables#93]
Hi there,

I would like to know how I can Align Images  same with Texts.
As you can see here: https://abs-holidays.com/china-ground-arrangement/

The PDF icon is below the line and not in a same row with texts.

Thank you in advance

**Comment by JohnTendik** [comment]
Looks like your theme has custom table styles that are interfering. You will need to add custom CSS to position the cell text manually. :)

**Comment by JohnTendik** [comment]
![image](https://user-images.githubusercontent.com/4714913/71424823-1474b780-2664-11ea-8fd7-d177652d65f9.png)

**Comment by Rashuz** [comment]
Good day & Merry Christmas!

Thank you for your reply.

As you can see my Text line and Image is not Aligned in the center.

I have added many custom css with valign, align and padding height but it is not working.
Could you please assist me.

Thank you
![Table2](https://user-images.githubusercontent.com/59174496/71433166-78f14e80-2718-11ea-85fb-b44b96f6a6d9.png)

**Comment by JohnTendik** [comment]
Merry Christmas! 

It looks like you've figured it out? Let me know if you still need help :) 

JT
